const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: [
    './**/*.php',
    './template-parts/**/*.php',
    './inc/**/*.php',
    './assets/js/**/*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
      spacing: {
        '9/16': '56.25%',
      },
      letterSpacing: {
        tighter: '-0.02em',
        tight: '-0.01em',
        normal: '0',
        wide: '0.01em',
        wider: '0.02em',
        widest: '0.4em',
      },
      colors: {
        zinc: {
          50: '#fafafa',
          100: '#f4f4f5',
          200: '#e4e4e7',
          300: '#d4d4d8',
          400: '#a1a1aa',
          500: '#71717a',
          600: '#52525b',
          700: '#3f3f46',
          800: '#27272a',
          900: '#18181b',
        },
        teal: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#0f766e',
          800: '#115e59',
          900: '#134e4a',
        },
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.zinc.600'),
            '--tw-prose-headings': theme('colors.zinc.900'),
            '--tw-prose-links': theme('colors.teal.500'),
            '--tw-prose-links-hover': theme('colors.teal.600'),
            '--tw-prose-underline': theme('colors.teal.500 / 0.3'),
            '--tw-prose-underline-hover': theme('colors.teal.500'),
            '--tw-prose-bold': theme('colors.zinc.900'),
            '--tw-prose-counters': theme('colors.zinc.500'),
            '--tw-prose-bullets': theme('colors.zinc.300'),
            '--tw-prose-hr': theme('colors.zinc.900 / 0.05'),
            '--tw-prose-quote-borders': theme('colors.zinc.200'),
            '--tw-prose-captions': theme('colors.zinc.500'),
            '--tw-prose-code': theme('colors.zinc.700'),
            '--tw-prose-code-bg': theme('colors.zinc.300 / 0.2'),
            '--tw-prose-pre-code': theme('colors.zinc.100'),
            '--tw-prose-pre-bg': theme('colors.zinc.900'),
            '--tw-prose-pre-border': 'transparent',
            '--tw-prose-th-borders': theme('colors.zinc.200'),
            '--tw-prose-td-borders': theme('colors.zinc.100'),
          },
        },
        invert: {
          css: {
            '--tw-prose-body': theme('colors.zinc.400'),
            '--tw-prose-headings': theme('colors.zinc.100'),
            '--tw-prose-links': theme('colors.teal.400'),
            '--tw-prose-links-hover': theme('colors.teal.300'),
            '--tw-prose-underline': theme('colors.teal.400 / 0.3'),
            '--tw-prose-underline-hover': theme('colors.teal.400'),
            '--tw-prose-bold': theme('colors.zinc.100'),
            '--tw-prose-counters': theme('colors.zinc.400'),
            '--tw-prose-bullets': theme('colors.zinc.600'),
            '--tw-prose-hr': theme('colors.zinc.100 / 0.05'),
            '--tw-prose-quote-borders': theme('colors.zinc.700'),
            '--tw-prose-captions': theme('colors.zinc.400'),
            '--tw-prose-code': theme('colors.zinc.300'),
            '--tw-prose-code-bg': theme('colors.zinc.200 / 0.05'),
            '--tw-prose-pre-code': theme('colors.zinc.100'),
            '--tw-prose-pre-bg': 'rgb(0 0 0 / 0.4)',
            '--tw-prose-pre-border': theme('colors.zinc.200 / 0.1'),
            '--tw-prose-th-borders': theme('colors.zinc.700'),
            '--tw-prose-td-borders': theme('colors.zinc.800'),
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
